name: My Workflow
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          npm install
          npm run build
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
      - name: Wait for Render Deployment
        uses: bounceapp/render-action@0.6.0
        with:
          render-token: ${{ secrets.RENDER_TOKEN }}
          github-token: ${{ secrets.TOKEN }}
          service-id: srv-cgksc9seoogkndl3t3qg
          retries: 20
          wait: 16000
          sleep: 30000
